"""Self-contained HTML research report generator."""

from __future__ import annotations

from datetime import datetime

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Kairos Research Report — {token}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         background: #0d1117; color: #c9d1d9; padding: 40px; line-height: 1.6; }}
  .report {{ max-width: 900px; margin: 0 auto; }}
  .header {{ border-bottom: 1px solid #30363d; padding-bottom: 20px; margin-bottom: 30px; }}
  .header h1 {{ font-size: 2rem; color: #58a6ff; }}
  .header .meta {{ color: #8b949e; font-size: 0.9rem; margin-top: 8px; }}
  .decision-banner {{
    padding: 20px; border-radius: 8px; margin-bottom: 24px;
    border-left: 6px solid {banner_color};
    background: {banner_bg};
  }}
  .decision-banner h2 {{ font-size: 1.5rem; color: {banner_color}; }}
  .decision-banner .conf {{ font-size: 1.1rem; margin-top: 4px; }}
  .decision-banner .rationale {{ color: #8b949e; margin-top: 8px; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }}
  .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; }}
  .card h3 {{
    font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em;
    color: #8b949e; margin-bottom: 12px;
  }}
  .metric {{ display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #21262d; }}
  .metric:last-child {{ border-bottom: none; }}
  .metric .label {{ color: #8b949e; }}
  .metric .value {{ font-weight: 600; }}
  .positive {{ color: #3fb950; }}
  .negative {{ color: #f85149; }}
  .neutral {{ color: #d29922; }}
  .footer {{ border-top: 1px solid #30363d; padding-top: 16px; margin-top: 30px; color: #8b949e; font-size: 0.85rem; }}
  table {{ width: 100%; border-collapse: collapse; }}
  td {{ padding: 6px 8px; border-bottom: 1px solid #21262d; }}
  @media (max-width: 600px) {{ .grid {{ grid-template-columns: 1fr; }} }}
</style>
</head>
<body>
<div class="report">
  <div class="header">
    <h1>Kairos Research Report</h1>
    <div class="meta">{token} | {market_type} | {strategy_name} | Generated {date}</div>
  </div>

  <div class="decision-banner">
    <h2>{decision}</h2>
    <div class="conf">Confidence: {confidence:.0%}</div>
    <div class="rationale">{rationale}</div>
  </div>

  <div class="grid">
    <div class="card">
      <h3>Technical Signals</h3>
      <div class="metric"><span class="label">Composite Score</span><span class="value">{composite:.0f}/100</span></div>
      <div class="metric"><span class="label">RSI(14)</span><span class="value">{rsi:.1f}</span></div>
      <div class="metric"><span class="label">Signal</span><span class="value {signal_class}">{signal}</span></div>
      <div class="metric"><span class="label">ADX</span><span class="value">{adx:.1f}</span></div>
      <div class="metric"><span class="label">ATR</span><span class="value">{atr:.2f}</span></div>
    </div>
    <div class="card">
      <h3>Risk Assessment</h3>
      <div class="metric"><span class="label">VaR(95%)</span><span class="value">{var_95:.2%}</span></div>
      <div class="metric"><span class="label">CVaR(95%)</span><span class="value">{cvar:.2%}</span></div>
      <div class="metric"><span class="label">Kelly Fraction</span><span class="value">{kelly:.2f}</span></div>
      <div class="metric"><span class="label">Status</span><span class="value {status_class}">{status}</span></div>
    </div>
  </div>

  <div class="grid">
    <div class="card">
      <h3>Market Data</h3>
      <div class="metric"><span class="label">Current Price</span><span class="value">${price:.2f}</span></div>
      <div class="metric"><span class="label">Data Points</span><span class="value">{n_bars}</span></div>
      <div class="metric"><span class="label">Strategy</span><span class="value">{strategy_name}</span></div>
    </div>
    <div class="card">
      <h3>Agent Pipeline</h3>
      {agent_trace}
    </div>
  </div>

  <div class="footer">
    <p>Generated by Kairos — AI Trading Agents, Fully Transparent &amp; Verifiable</p>
    <p>This report is for research purposes only. Not financial advice.</p>
  </div>
</div>
</body>
</html>"""


def generate_html_report(
    token: str,
    market_type: str,
    strategy_name: str,
    decision: str,
    confidence: float,
    rationale: str,
    composite: float,
    rsi: float,
    signal: str,
    adx: float,
    atr: float,
    var_95: float,
    cvar: float,
    kelly: float,
    is_safe: bool,
    price: float,
    n_bars: int,
    agent_traces: list[dict] | None = None,
) -> str:
    """Generate a self-contained HTML research report."""
    decision_colors = {"BUY": "#3fb950", "SELL": "#f85149", "HOLD": "#d29922"}
    dc = decision_colors.get(decision, "#8b949e")
    signal_class = "positive" if signal == "bullish" else ("negative" if signal == "bearish" else "neutral")
    status = "Safe" if is_safe else "Caution"
    status_class = "positive" if is_safe else "negative"

    agent_html = ""
    if agent_traces:
        for at in agent_traces:
            name = at.get("agent_name", "?").title()
            conf = at.get("confidence", 0)
            reasoning = at.get("reasoning", "")[:80]
            agent_html += (
                f'<div class="metric"><span class="label">{name}</span>'
                f'<span class="value">{conf:.0%} — {reasoning}</span></div>\n'
            )
    else:
        agent_html = '<div class="metric"><span class="label">Research → Quant → Risk → Executor</span></div>'

    return TEMPLATE.format(
        token=token,
        market_type=market_type.title(),
        strategy_name=strategy_name,
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        decision=decision,
        confidence=confidence,
        rationale=rationale,
        composite=composite,
        rsi=rsi,
        signal=signal.upper() if signal else "?",
        signal_class=signal_class,
        adx=adx,
        atr=atr,
        var_95=var_95,
        cvar=cvar,
        kelly=kelly,
        status=status,
        status_class=status_class,
        price=price,
        n_bars=n_bars,
        banner_color=dc,
        banner_bg=f"#{'0d2818' if decision == 'BUY' else '280d0d' if decision == 'SELL' else '282018'}",
        agent_trace=agent_html,
    )
